language: generic
sudo: required
services: 
  - docker

before_install: 
  - docker build -t sanveersingh/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true sanveersingh/react-test npm test 

after_success: 
  - docker build -t sanveersingh/multi-client ./client
  - docker build -t sanveersingh/multi-nginx ./nginx 
  - docker build -t sanveersingh/multi-server ./server 
  - docker build -t sanveersingh/multi-worker ./server 
