language: generic
sudo: required
services: 
  - docker

before_install: 
  - docker build -t sanveersingh/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true sanveersingh/react-test npm test 

after_success: 
  - docker build -t sanveersingh/multi-client ./client
  - docker build -t sanveersingh/multi-nginx ./nginx 
  - docker build -t sanveersingh/multi-server ./server 
  - docker build -t sanveersingh/multi-worker ./server 
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  # Take those images adn push them to docker hub
  - docker push sanveersingh/multi-client
  - docker push sanveersingh/multi-nginx
  - docker push sanveersingh/multi-server
  - docker push sanveersingh/multi-worker

deploy: 
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "multi-docker"
  env: "Multi-docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-263354746789"
  bucket_path: "multi-docker"
  on: 
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
